# =================================================================
# eaSway - Foot Terminal Configuration
# Estética: Neobrutalista / Post-Punk
# =================================================================
[main]
font=Noto Sans Mono Bold:size=11
dpi-aware=yes
pad=15x15

[cursor]
color=000000 00ff00
blink=yes

[colors]
background=000000
foreground=ffffff
regular0=000000
regular1=ff0000
regular2=00ff00
regular3=ffff00
regular4=0000ff
regular5=ff00ff
regular6=00ffff
regular7=ffffff
bright0=444444
bright1=ff5555
bright2=55ff55
bright3=ffff55
bright4=5555ff
bright5=ff55ff
bright6=55ffff
bright7=ffffff

[key-bindings]
spawn-terminal=Control+Shift+n