font_family      Noto Sans Mono Bold
font_size        11.0
cursor           #00ff00
cursor_shape     block
shell_integration disabled

foreground       #ffffff
background       #000000

color0 #000000
color8 #444444
color1 #ff0000
color9 #ff5555
color2 #00ff00
color10 #55ff55

window_padding_width 15
confirm_os_window_close 0